Spec `ExecutionState::STOP`
privacy-scaling-explorations/zkevm-specs pull request #100
Opened 2022-01-20 14:05 UTC by han0110

This PR is once part of #82, and aims to spec out `ExecutionState::STOP`.

It depends on #99.

2022-01-27 17:32 UTC, ed255 approved these changes

2022-01-27 17:33 UTC, ed255 requested changes

2022-01-27 17:33 UTC, ed255 commented on specs/opcode/00STOP.md
> +1. If it's an root call, it handles the gas refund and coinbase reward, then goes to next transaction by checking the next step has increased `tx_id`.
I hit approve by mistake, so I had to add a comment to change my review status.

2022-01-29 10:36 UTC, han0110 commented on specs/opcode/00STOP.md
> +1. If it's an root call, it handles the gas refund and coinbase reward, then goes to next transaction by checking the next step has increased `tx_id`.
Yes, it's handled by `EndTx`. Fixed.

2022-01-31 11:16 UTC, ed255 approved these changes
LGTM!

2022-04-27 15:49 UTC, ed255 approved these changes
I've left two small comments but everything looks correct to me :)
I'm approving the PR already, feel free to check the comments and discuss!

2022-04-27 15:51 UTC, ed255 commented
BTW, the current branch conflicts seem to come from https://github.com/appliedzkp/zkevm-specs/pull/185 and should be very easy to resolve.

2022-04-27 15:52 UTC, han0110 commented on src/zkevm_specs/evm/execution/stop.py
> +            rw_counter=Transition.delta(13),
Yes, this approach is much easier to follow, let me update it!

2022-04-27 16:09 UTC, han0110 commented on src/zkevm_specs/evm/execution/stop.py
> +            rw_counter=Transition.delta(13),
Fixed in [`7546f8b`](https://github.com/appliedzkp/zkevm-specs/pull/100/commits/7546f8b3360320052db1d12204f3f5b21783fb1e)

2022-06-29 23:48 UTC, icemelon reviewed
LGTM. Just two minor comments.

2022-06-29 23:49 UTC, icemelon approved these changes

2022-07-01 06:05 UTC, icemelon commented on src/zkevm_specs/evm/execution/calldatacopy.py
> -        assert instruction.next is not None
Nope, just curious.

2022-07-01 06:45 UTC, merged