[WIP] mload mstore and mstore8 opcode modification
privacy-scaling-explorations/zkevm-specs pull request #358
Opened 2023-01-17 04:37 UTC by ashWhiteHat

2023-02-06 05:31 UTC, han0110 reviewed
Overall LGMT. Nice refactor! Just got a small question about the `stack_pointer`

2023-02-06 05:31 UTC, han0110 commented on src/zkevm_specs/evm/execution/memory.py
> +        stack_pointer=Transition.delta(is_store * -2),
Should increase the `stack_pointer` if it's store (pop 2 elements)?

```suggestion
        stack_pointer=Transition.delta(is_store * 2),
```

2023-02-06 05:31 UTC, han0110 commented on tests/evm/test_memory.py
> +    stack_pointer = 1020 + (is_mload * 2)
```suggestion
    stack_pointer = 1022 + (is_store * 2)
```

2023-02-06 06:20 UTC, ashWhiteHat commented
Hi @han0110 
Thank you for the review!
It was weird as you mentioned.
I modified according to your review.

I would appreciate it if you could confirm.
Thank you!

2023-02-06 06:21 UTC, han0110 approved these changes
LGTM now!

2023-02-07 13:18 UTC, ed255 requested changes

2023-02-07 13:18 UTC, ed255 commented on src/zkevm_specs/evm/execution/memory.py
> +        instruction.memory_lookup(RW.Write, address.expr())
```suggestion
        instruction.is_equal(instruction.memory_lookup(RW.Write, address.expr()), value.le_bytes[0])
```
Add equality check to value with the lookup

2023-02-07 13:18 UTC, ed255 commented on src/zkevm_specs/evm/execution/memory.py
> +            )
```suggestion
            instruction.is_equal(instruction.memory_lookup(
                RW.Write if is_store == FQ(1) else RW.Read, address.expr() + idx, src_id
            ), value.le_bytes[31-idx])
```
Add equality check to value with the lookup

2023-02-07 13:18 UTC, ed255 commented on src/zkevm_specs/evm/execution/memory.py
> +    src_id = instruction.call_context_lookup(CallContextFieldTag.TxId)
I didn't find this lookup in the circuit.  I see that you use it in the `memory_lookup`, but that function takes a `call_id` and not a `tx_id`.  So I think this should be removed, and the `memory_lookup` for `is_not_mstore8` should get the 3rd parameter removed (the `src_id`).

2023-02-08 01:34 UTC, ashWhiteHat commented
Hi @ed255
Thank you for the review.
Your suggestion makes sense to me and I changed PR accordingly.

I would appreciate it if you could confirm.
Thank you!

2023-02-08 14:59 UTC, ed255 approved these changes
LGTM! Thanks for working on this update!

2023-02-09 00:09 UTC, merged