Markdown doc for `ErrorOutOfGasSloadSstore` state
privacy-scaling-explorations/zkevm-specs pull request #381
Opened 2023-02-09 06:12 UTC by silathdiir

Circuit issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1119

Circuit PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1147

2023-02-23 13:02 UTC, han0110 approved these changes
LGTM!

2023-02-23 15:47 UTC, miha-stopar approved these changes
LGTM!

2023-02-24 03:34 UTC, KimiWu123 requested changes

2023-02-24 03:34 UTC, KimiWu123 commented on specs/error_state/ErrorOutOfGasSloadSstore.md
> +  if value == original_value:
Here should be `!=`. If it's a `==` which means `original_value = value == 0 & value != value_prev` ==> e.g. 0 --> non-zero --> 0. In this case, gas_cost should be `SLOAD_GAS` only.

2023-02-24 04:13 UTC, KimiWu123 commented on specs/error_state/ErrorOutOfGasSloadSstore.md
> +  if value == original_value:
I think to use `original_eq_prev` [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1147/files#diff-08d58ebc59ab6c11bf7c049e859441eed2319a03feb3fdffaddaba73f8a8c829R719-R724) is incorrect. 

Let's see the case, `value_eq_prev == false && original_eq_prev == false`, the `gas_cost` would be `WARM_ACCESS`. The case means `original_value != value_pre != value` but it doesn't imply `original_value == value` and I can't find any contraints for this equivalence (correct me if I missed it).

So, I think to follow the spec here (using `value != original_value`) is correct.

2023-02-27 02:45 UTC, KimiWu123 approved these changes

2023-03-01 02:55 UTC, merged